version: '3.8'

services:
  db:
    image: postgres:15  
    container_name: postgres_db-gym-elegance
    restart: always
    environment:
      POSTGRES_USER: postgres  
      POSTGRES_PASSWORD: ${DB_PASSWORD}  
      POSTGRES_DB: ${DB_NAME}  
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data  
      - ./assets/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  
  postgres_data:
